let login = require('./login/login')
let userLogin = require('./login/userLogin')
let userList = require('./userList/index')
let deleteUser = require('./deleteUser/index')
let addUser = require('./addUser/index')
let chapters = require('./chapters/index')
let trueTopics = require('./trueTopics/index')
let simulation = require('./simulation/index')
let denseVolume = require('./denseVolume/index')
module.exports = function (app, connection) {
  login(app, connection)
  userList(app, connection)
  deleteUser(app, connection)
  addUser(app, connection)
  chapters(app, connection)
  trueTopics(app, connection)
  simulation(app, connection)
  denseVolume(app, connection)
  userLogin(app, connection)
}